export const GET_MOVIES_ON_LOAD = 'GET_MOVIES_ON_LOAD';
export const GET_MOVIES_ON_SEARCH = 'GET_MOVIES_ON_SEARCH';
export const GET_MORE_MOVIES = 'GET_MORE_MOVIES';
export const GET_GENRES = 'GET_GENRES';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_CREDITS = 'GET_CREDITS';
export const GET_PERSON = 'GET_PERSON';
export const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';
